export const JAPANESE_TEAM_NAMES_BY_SLUG: Record<string, string> = {
  argentina: "アルゼンチン",
  australia: "オーストラリア",
  bath: "バース",
  bayonne: "バイヨンヌ",
  benetton: "ベネトン",
  blues: "ブルーズ",
  "bordeaux-begles": "ボルドー",
  "bristol-bears": "ブリストル・ベアーズ",
  brumbies: "ブランビーズ",
  bulls: "ブルズ",
  canada: "カナダ",
  cardiff: "カーディフ",
  castres: "カストル",
  chiefs: "チーフス",
  chile: "チリ",
  clermont: "クレルモン",
  connacht: "コノート",
  crusaders: "クルセイダーズ",
  dragons: "ドラゴンズ",
  edinburgh: "エディンバラ",
  england: "イングランド",
  "exeter-chiefs": "エクセター・チーフス",
  "fijian-drua": "フィジアン・ドルア",
  fiji: "フィジー",
  force: "ウェスタン・フォース",
  france: "フランス",
  georgia: "ジョージア",
  "glasgow-warriors": "グラスゴー・ウォリアーズ",
  gloucester: "グロスター",
  grenoble: "グルノーブル",
  harlequins: "ハーレクインズ",
  highlanders: "ハイランダーズ",
  "hong-kong-china": "ホンコンチャイナ",
  hurricanes: "ハリケーンズ",
  ireland: "アイルランド",
  italy: "イタリア",
  japan: "日本",
  "la-rochelle": "ラ・ロシェル",
  "leicester-tigers": "レスター・タイガース",
  leinster: "レンスター",
  lions: "ライオンズ",
  lyon: "リヨン",
  "moana-pasifika": "モアナ・パシフィカ",
  montpellier: "モンペリエ",
  munster: "マンスター",
  namibia: "ナミビア",
  "new-zealand": "ニュージーランド",
  "newcastle-falcons": "ニューカッスル・ファルコンズ",
  "northampton-saints": "ノーザンプトン・セインツ",
  ospreys: "オスプレイズ",
  pau: "ポー",
  perpignan: "ペルピニャン",
  portugal: "ポルトガル",
  "racing-92": "ラシン92",
  rebels: "メルボルン・レベルズ",
  reds: "クイーンズランド・レッズ",
  romania: "ルーマニア",
  "sale-sharks": "セール・シャークス",
  samoa: "サモア",
  saracens: "サラセンズ",
  scarlets: "スカーレッツ",
  scotland: "スコットランド",
  sharks: "シャークス",
  "south-africa": "南アフリカ",
  spain: "スペイン",
  "stade-francais": "スタッド・フランセ",
  stormers: "ストーマーズ",
  tonga: "トンガ",
  toulon: "トゥーロン",
  toulouse: "トゥールーズ",
  ulster: "アルスター",
  uruguay: "ウルグアイ",
  usa: "アメリカ",
  vannes: "ヴァンヌ",
  wales: "ウェールズ",
  waratahs: "ワラターズ",
  zebre: "ゼブレ・パルマ",
  zimbabwe: "ジンバブエ",
};

export const JAPANESE_COMPETITION_NAMES_BY_FAMILY: Record<string, string> = {
  "autumn-nations": "オータムネーションズシリーズ",
  "nations-championship": "ネーションズチャンピオンシップ",
  "league-one": "ジャパンラグビー リーグワン",
  "pacific-nations-cup": "パシフィック・ネーションズカップ",
  pnc: "パシフィック・ネーションズカップ",
  premiership: "プレミアシップ",
  "rugby-championship": "ザ・ラグビーチャンピオンシップ",
  rwc: "ラグビーワールドカップ",
  "six-nations": "シックスネイションズ",
  "super-rugby-pacific": "スーパーラグビー・パシフィック",
  "top-14": "トップ14",
  urc: "ユナイテッド・ラグビー・チャンピオンシップ",
};

export function inferCompetitionFamilyFromSlug(slug?: string | null) {
  if (!slug) {
    return null;
  }

  return slug.replace(/-\d{4}(-\d{2})?$/, "");
}
