import { describe, expect, it } from "vitest";

import {
  containsRosterEnumeration,
  containsContradictedZeroStatClaim,
  containsUngroundedPlayerReference,
  containsUnsupportedStatistic,
  hasConfirmedSourcedFactLineup,
} from "@/lib/content/fabrication-guard";
import { buildJrfuLineupSourcedFacts } from "@/lib/llm/sourced-facts/fetch";

import type { SourcedFactInput } from "@/lib/llm/types";

const fabricatedPreview = `
# セクション2: キープレイヤーとマッチアップ

山澤拓也（フライハーフ）は地域獲得の起点になり、中野将伍（センター）はゲインラインで強みを見せる。
藤原信（スクラムハーフ）のテンポ管理も勝敗を左右する。
`;

const confirmedJrfuLineupFacts = buildJrfuLineupSourcedFacts({
  announced_at: "2026-08-13T00:00:00.000Z",
  japan_players: [
    { is_starter: true, jersey_number: 1, name: "岡部崇人" },
    { is_starter: true, jersey_number: 2, name: "江良颯" },
    { is_starter: true, jersey_number: 3, name: "竹内柊平" },
  ],
  opponent_name: "オーストラリア代表",
  opponent_players: [
    { is_starter: true, jersey_number: 1, name: "James Slipper" },
    { is_starter: true, jersey_number: 2, name: "Billy Pollard" },
    { is_starter: true, jersey_number: 3, name: "Allan Alaalatoa" },
  ],
  source_url: "https://www.rugby-japan.jp/match/30035",
});

const noPlayerReferenceData = {
  hasConfirmedSourcedFactLineup: false,
  hasEvents: false,
  hasLineups: false,
};

const rosterEnumerationSection = `
## 前方の密度と9番・10番の選択が攻撃の輪郭を決める
南アフリカは1番オックス・ンチェ、2番マルコム・マークス、3番ウィルコ・ラウを先発させ、4番エベン・エツベト、5番ルアン・ノーチェが続く。後方には9番グラント・ウィリアムズ、10番サーシャ・ファインバーグ＝ムンゴメズル、12番ダミアン・デアレンデ、13番ジェシー・クリエル、14番チェスリン・コルビ、15番ダミアン・ヴィレムセが並ぶ。ベンチには16番ヤン＝ヘンドリク・ウェッセルズ、22番コーバス・ライナッハ、23番マニー・リボックが控える構成だ。
一方のニュージーランドは、1番イーサン・デ・グルート、2番コーディー・テイラー、3番タイレル・ローマックスを前列に置き、4番ジョシュ・ロードと5番ファビアン・ホランドを先発させる。後方には9番コルテス・ラティマ、10番ボーデン・バレット、12番ジョーディー・バレット、13番リーコ・イオアネ、14番ウィル・ジョーダン、15番ダミアン・マッケンジーが並ぶ。ベンチには16番サミソニ・タウケイアホ、20番ピーター・ラカイ、21番フィンレイ・クリスティー、22番クイン・トゥパエア、23番ジョシュ・ジャコムが控える。`;
const rosterEnumerationArticle = rosterEnumerationSection.padEnd(1_944, "分析");

describe("containsUngroundedPlayerReference", () => {
  it("detects key-player style player mentions when lineups and events are absent", () => {
    expect(
      containsUngroundedPlayerReference(
        fabricatedPreview,
        noPlayerReferenceData,
      ),
    ).toBe(true);
  });

  it("does not trigger when lineups are present", () => {
    expect(
      containsUngroundedPlayerReference(fabricatedPreview, {
        ...noPlayerReferenceData,
        hasLineups: true,
      }),
    ).toBe(false);
  });

  it("does not trigger when events are present", () => {
    expect(
      containsUngroundedPlayerReference(fabricatedPreview, {
        ...noPlayerReferenceData,
        hasEvents: true,
      }),
    ).toBe(false);
  });

  it("does not trigger when confirmed JRFU lineup facts are present", () => {
    expect(
      containsUngroundedPlayerReference(fabricatedPreview, {
        ...noPlayerReferenceData,
        hasConfirmedSourcedFactLineup: hasConfirmedSourcedFactLineup(
          confirmedJrfuLineupFacts,
        ),
      }),
    ).toBe(false);
  });

  it("does not block team-level tactical preview copy without player context", () => {
    expect(
      containsUngroundedPlayerReference(
        "日本はキックチェイスと接点の精度、イタリアはセットピースの圧力が焦点になる。",
        noPlayerReferenceData,
      ),
    ).toBe(false);
  });
});

describe("hasConfirmedSourcedFactLineup", () => {
  it("recognizes the fact format generated by buildJrfuLineupSourcedFacts", () => {
    expect(confirmedJrfuLineupFacts[0]?.fact).toBe(
      "日本代表の先発は1 岡部崇人、2 江良颯、3 竹内柊平。",
    );
    expect(hasConfirmedSourcedFactLineup(confirmedJrfuLineupFacts)).toBe(true);
  });

  it("requires high confidence", () => {
    expect(
      hasConfirmedSourcedFactLineup(
        confirmedJrfuLineupFacts.map((fact) => ({
          ...fact,
          confidence: "medium" as const,
        })),
      ),
    ).toBe(false);
  });

  it("rejects non-lineup facts and lineup claims without a player list", () => {
    expect(
      hasConfirmedSourcedFactLineup([
        {
          confidence: "high",
          fact: "会場はタウンズビルのQueensland Country Bank Stadium。",
          source_domain: "rugby-japan.jp",
          source_url: "https://www.rugby-japan.jp/match/30035",
        },
        {
          confidence: "high",
          fact: "気温は23度が予想される。",
          source_domain: "rugby-japan.jp",
          source_url: "https://www.rugby-japan.jp/match/30035",
        },
      ]),
    ).toBe(false);
    expect(
      hasConfirmedSourcedFactLineup([
        {
          confidence: "high",
          fact: "両チームとも先発を大幅に入れ替えた。",
          source_domain: "rugby-japan.jp",
          source_url: "https://www.rugby-japan.jp/match/30035",
        },
      ]),
    ).toBe(false);
  });

  it("recognizes comma-separated player names and ignores empty runtime values", () => {
    expect(
      hasConfirmedSourcedFactLineup([
        {
          confidence: "high",
          fact: "starting XV は山田太郎、田中次郎、佐藤三郎。",
          source_domain: "example.com",
          source_url: "https://example.com/lineup",
        },
      ]),
    ).toBe(true);
    expect(hasConfirmedSourcedFactLineup([])).toBe(false);
    expect(
      hasConfirmedSourcedFactLineup([
        null as unknown as SourcedFactInput,
        { confidence: "high", fact: "" } as unknown as SourcedFactInput,
        { confidence: "high", fact: null } as unknown as SourcedFactInput,
      ]),
    ).toBe(false);
  });
});

describe("containsRosterEnumeration", () => {
  it("detects the published-style roster section when it occupies a material share of the article", () => {
    expect(rosterEnumerationArticle.length).toBeGreaterThan(1_500);
    expect(containsRosterEnumeration(rosterEnumerationArticle)).toBe(true);
  });

  it("does not detect two named players when each has an individual selection rationale", () => {
    expect(
      containsRosterEnumeration(
        "9番グラント・ウィリアムズは素早い球出しで接点の優位を攻撃へつなぐ。10番サーシャ・ファインバーグ＝ムンゴメズルはキックで相手を自陣へ押し戻す役割を担う。",
      ),
    ).toBe(false);
  });

  it("does not detect copy without player names", () => {
    expect(
      containsRosterEnumeration(
        "南アフリカは接点の圧力を起点にし、ニュージーランドはキックチェイスの精度で対抗する。",
      ),
    ).toBe(false);
  });
});

describe("containsUnsupportedStatistic", () => {
  it("detects kick attempt ratio phrasing without source support", () => {
    expect(containsUnsupportedStatistic("彼は7回中5回成功させた")).toBe(true);
    expect(
      containsUnsupportedStatistic(
        "コルベはコンバージョンを12回中10回成功させた",
      ),
    ).toBe(true);
  });

  it("keeps existing unsupported statistic detections", () => {
    expect(containsUnsupportedStatistic("成功率は80%だった")).toBe(true);
    expect(containsUnsupportedStatistic("テリトリーで優位に立った")).toBe(true);
    expect(containsUnsupportedStatistic("支配率の差が出た")).toBe(true);
  });

  it("detects ungrounded penalty discipline claims", () => {
    expect(
      containsUnsupportedStatistic(
        "アイルランドは反則なしのクリーンなプレーで勝利した",
      ),
    ).toBe(true);
    expect(
      containsUnsupportedStatistic(
        "アイルランドは反則を犯さないプレーで試合を支配した",
      ),
    ).toBe(true);
  });

  it("allows penalty discipline claims when penalty facts support them", () => {
    expect(
      containsUnsupportedStatistic("アイルランドは反則が少なかった", [
        "ホームチームのペナルティ5",
      ]),
    ).toBe(false);
  });

  it("does not treat penalty goal wording as an unsupported statistic", () => {
    expect(
      containsUnsupportedStatistic("アイルランドはペナルティゴールを決めた"),
    ).toBe(false);
  });
});

describe("containsContradictedZeroStatClaim", () => {
  it("detects penalty zero claims contradicted by team_stats", () => {
    expect(
      containsContradictedZeroStatClaim(
        "アイルランドは反則を犯さず、規律あるプレーで日本を封じ込めた",
        {
          away: { penalties_conceded: 9 },
          home: { penalties_conceded: 9 },
        },
      ),
    ).toBe(true);
  });

  it("detects non-penalty count stat zero claims", () => {
    expect(
      containsContradictedZeroStatClaim(
        "日本はターンオーバーなしで試合を進めた",
        {
          away: { turnovers: 3 },
          home: { turnovers: 5 },
        },
      ),
    ).toBe(true);
  });

  it("ignores non-zero penalty comparison claims", () => {
    expect(
      containsContradictedZeroStatClaim("日本は反則が多かった", {
        away: { penalties_conceded: 9 },
        home: { penalties_conceded: 9 },
      }),
    ).toBe(false);
  });

  it("does not flag zero claims when the stat is actually 0-0", () => {
    expect(
      containsContradictedZeroStatClaim("両チームとも反則なしで進めた", {
        away: { penalties_conceded: 0 },
        home: { penalties_conceded: 0 },
      }),
    ).toBe(false);
  });

  it("returns false when team_stats is unavailable", () => {
    expect(
      containsContradictedZeroStatClaim(
        "アイルランドは反則を犯さず試合を終えた",
        null,
      ),
    ).toBe(false);
  });
});
