export function HeroTexture() {
  return (
    <svg
      aria-hidden
      className="pointer-events-none absolute inset-0 z-[1] h-full w-full"
      preserveAspectRatio="xMidYMid slice"
      viewBox="0 0 1440 600"
      xmlns="http://www.w3.org/2000/svg"
    >
      <line
        stroke="white"
        strokeOpacity="0.04"
        strokeWidth="1.5"
        x1="720"
        x2="720"
        y1="0"
        y2="600"
      />
      <line
        stroke="white"
        strokeOpacity="0.03"
        strokeWidth="1"
        x1="288"
        x2="288"
        y1="0"
        y2="600"
      />
      <line
        stroke="white"
        strokeOpacity="0.03"
        strokeWidth="1"
        x1="1152"
        x2="1152"
        y1="0"
        y2="600"
      />
      <line
        stroke="white"
        strokeOpacity="0.025"
        strokeWidth="1"
        x1="72"
        x2="72"
        y1="0"
        y2="600"
      />
      <line
        stroke="white"
        strokeOpacity="0.025"
        strokeWidth="1"
        x1="1368"
        x2="1368"
        y1="0"
        y2="600"
      />
      <line
        stroke="white"
        strokeOpacity="0.03"
        strokeWidth="1"
        x1="0"
        x2="1440"
        y1="300"
        y2="300"
      />
      <circle
        cx="720"
        cy="300"
        fill="none"
        r="80"
        stroke="white"
        strokeOpacity="0.04"
        strokeWidth="1.5"
      />
      <ellipse
        cx="720"
        cy="300"
        fill="none"
        rx="160"
        ry="110"
        stroke="white"
        strokeOpacity="0.025"
        strokeWidth="1"
      />
    </svg>
  );
}
